{
 "title": "Flink Dashboard",
 "description": "flink with prometheus",
 "tags": [ "flink" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job_name", "label": "job_name", "query": { "query": "label_values(job_name)" } }
  ]
 },
 "panels": [
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "number of TaskManagers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  { "title": "BackPressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "numRecordsOutPerSecond",
   "type": "graph",
   "description": "numRecordsOutPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "numRecordsInPerSecond",
   "type": "graph",
   "description": "umRecordsInPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc count"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc count"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc时间"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc时间"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} taskManger live Thread counts"
    }
   ]
  },
  { "title": "CheckPoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "lastCheckpointDuration",
   "type": "graph",
   "description": "lastCheckpointDuration",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "Last CheckPoint Size",
   "type": "graph",
   "description": "Last CheckPoint Size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "description": "numberOfFailedCheckpoints",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_FailedCheckpoints"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max-flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Available",
   "type": "graph",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "graph",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  }
 ]
}